### ISSUE TITLE
The information saved in function "qUnsigned" seems wrong

### ISSUE THREAD

**Issue by Wang-Qk** [PannenetsF/TQT#3]
In file `tqt/function/number.py`, the function `qUnsigned` saves `round(x/s)` in ctx, but accodring to the gradient equations in the paper,  the floating point value `x/s` should be saved for the computing in backward.
Is it wrong, or something I misunderstand?

https://github.com/PannenetsF/TQT/blob/6397a57225f83e2075900678c60ffed35f64f20b/tqt/function/number.py#L81

**Comment by PannenetsF** [comment]
Oops, it seems to be a typo in qU. Thanks for the issue.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Thu, Dec 16, 2021 18:15 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [PannenetsF/TQT] The information saved in function "qUnsigned" seemswrong (Issue #3)




 
In file tqt/function/number.py, the function qUnsigned saves round(x/s) in ctx, but accodring to the gradient equations in the paper,  the floating point value x/s should be saved for the computing in backward.
 Is it wrong, or something I misunderstand?
 
https://github.com/PannenetsF/TQT/blob/6397a57225f83e2075900678c60ffed35f64f20b/tqt/function/number.py#L81
